server:
  port: 1002

helmet:
  mqtt:
    emqx:
      username: admin
      password: public
      #tcp://ip:port
      host-url : tcp://39.96.68.13:1883
      client-id : helmet_server_subscribe
      default-topic : helmet_topic
      timeout : 60
      keep-alive : 60
      #qos 可以取值0,1,2
      q-os: 0
spring:
  datasource:
    url: jdbc:mysql://39.96.68.13:3306/helmet?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Maqi@1466
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect